name: go-main

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7
        with:
          go-version: "1.25.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # version v9.3.0
        with:
          version: "v2.8.0"
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...
      - uses: qltysh/qlty-action/coverage@b413a89d8f3a8b36b9edd20b7ef1ad7ae0a7ac3a # version 2.2.2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.out
